version: "3.3"
services:
    redis:
        image: redis

    web:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 8079:80

    backend:
        build:
            context: backend
            dockerfile: ./Dockerfile
        environment:
            - SESSION_SECRET=uxd1n30d18c778
            - MAX_AGE=604800000
            - REDIS_CONNECTION=redis://redis:6379
        ports:
            - 8081:3000

    frontend:
        build:
            context: frontend
            dockerfile: ./Dockerfile
        ports:
            - 8080:3000
        depends_on:
            - backend
