version: '3.3'
services:
  backend:
    build: 
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 8081:3000
  
  frontend:
    build: 
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - backend